name: todo2

services:
  react:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - "./public/:/app/public/"
      - "./src/:/app/src/"
    restart: always
